#!/usr/bin/perl -Tw
#
# Name: MDR patient administration
# Auth: Wesley Schaal, wesley.schaal@farmbio.uu.se
# When: 2013-12-13

use DBI; use v5.10;
use CGI qw(:all *table *Tr *td *blockquote -nosticky);
use CGI::Carp qw(fatalsToBrowser);  autoEscape(undef);
require "./common.pl";

$appl = 'MDR Bacteria (VR/5011)';
$D=0;

# my $grp= "mdrusr";
# my $dbh = DBI->connect("DBI:mysql:"
# 	  . ";mysql_read_default_file=$ENV{HOME}/.my.cnf"
# 	  . ";mysql_read_default_group=$grp") ||
#     die "Can't connect to $db: $DBI::errstr";
my $dbf = '../data/bacteria.sqlite';
my $dbh = DBI->connect("dbi:SQLite:dbname=$dbf",'','');

($min,$hour,$day,$mon,$year) = (localtime)[1..5];
$year += 1900; $mon++;
$now = sprintf("Fetched: %4d-%02d-%02d at %02d:%02d",
		   $year,$mon,$day,$hour,$min);


for my $v (qw(mode submit))  { $$v = param($v); }
ShowHead();
if    ($mode eq 'pedt')  { Pat_Edt(); }
else                     { Pat_New(); }
ShowFoot();


sub Pat_New {
    @sids = @{ $dbh->selectcol_arrayref('select sid from sites order by sid') };
    $sql = 'select sid||": "||pi from sites order by sid';
    @sids{@sids} = @{ $dbh->selectcol_arrayref($sql) };
    unshift @sids,0; $sids{0} = ' - ';

    print start_blockquote, start_form;
    print h2('Add a patient to the database');
    print start_table({width=>'95%',border=>1,cellspacing=>0,cellpadding=>10});
    print start_Tr, start_td;
    print start_table({width=>'100%',cellpadding=>'5'}), start_Tr;
    print td(['Site' . br .
	      popup_menu(-name=>'sid',-values=>\@sids,-labels=>\%sids),
	      'Patient ID #' . br .
	      font({color=>'grey'},'generated by server'),
	      'Patient Code (ext)' . br .
	      textfield(-name=>'xid0',size=>'16',maxlength=>'64'),
	      'Age' . br .
	      textfield(-name=>'birth',size=>'4',maxlength=>'4'),
	      'Sex' . br .
	      popup_menu(-name=>'sex',-values=>['-','F','M'])]);
    print end_Tr, end_table;
    print end_td, end_Tr, end_table;

    print table({align=>'center',width=>'50%',cellspacing=>'10'},
		Tr(th([submit(-name=>'submit',value=>'Submit'),
		       defaults('Reset')])));
    print hidden(-name=>'mode',default=>'pnew',force=>1);
    print end_form, end_blockquote;

    Pat_Add() if $submit;
}


sub Pat_Add {
    #Pat_New(); print hr;
    print hr;

    for my $v (qw(sid xid0 birth sex))  { $$v = param($v); }
    $sid =~ y/0-9//cd;  $birth =~ y/0-9//cd;  $sex =~ y/MF//cd;
    $xid0 =~ s/^\s*|\s*$//g; $xid0 =~ s/\s/_/g; #report subst?
    #$xid0 =~ y/A-Za-z0-9.,ÅåÄäÖöÉéÈèÜü\/_-//cd;
    ($xid) = $xid0 =~ /([A-Za-z0-9.,ÅåÄäÖöÉéÈèÜü\/-]+)/;

    unless($sid) { Fret('Please specify a Site.'); return(); }

    my $ptab = sprintf "pat%04d", $sid; my $lid;
    my ($pid) = $dbh->selectrow_array("select pid from $ptab where xid='$xid'");

    if ($pid) {
	Fret("Patient Code '$xid' already registered for Site $sid. " . br .
	     "Use a new code if this is a new patient or " .
	     a({href=>url . "?mode=pedt;sid=$sid;pid=$pid"}, 'edit details') .
	     ' for this patient.');
    } elsif($xid ne $xid0) {
	Fret("Some unexpected characters found in Patient Code. " .
	     "Please fix or file an error report.");
    } elsif((!$birth && $birth ne '0') || $birth > $year) {
	Fret( "Missing or misunderstood age. " .
	      "Please enter approximate age in years (or year of birth).");
    } elsif(!$sex) {
	Fret('Please specify sex of patient.');
    } else {
	$birth = $year - $birth if $birth < 200;
	$dbh->do("insert into $ptab values (NULL,'$xid','$sex',$birth)");
	$pid = $dbh->last_insert_id(undef,undef,undef,undef);
	$lid = sprintf "P%04d-%04d", $sid, $pid;
	unless($xid) {
	    $xid = $lid;
	    $dbh->do("update $ptab set xid='$xid' where pid=$pid");
	    Fret("Patient Code not specified so will use '$xid'.");
	}
	print h3("Patient '$xid' has been registered with ID '$lid'.");
	print br,'For this patient, you may wish to: ',
	ul(li([a({href=>url . "?mode=pedt;sid=$sid;pid=$pid"}, 'Edit') . ' details or ',
	       a({href=>"infadm.cgi?sid=$sid;pid=$pid"}, 'Define') . ' an infection']));
	print p("To enter a new patient, simply change the details " .
		"above and click 'Submit' again.");
    }
}


sub Pat_Edt {
    for my $v (qw(sid pid))  { $$v = param($v); }
    $sid =~ y/0-9//cd;  $pid =~ y/0-9//cd;
    die("Completely Lost") unless ($sid && $pid);

    @sids = @{ $dbh->selectcol_arrayref('select sid from sites order by sid') };
    $sql = 'select sid||": "||pi from sites order by sid';
    @sids{@sids} = @{ $dbh->selectcol_arrayref($sql) };
    unshift @sids,0; $sids{0} = ' - ';
    @sexs = ('F','M'); @sexs{@sexs} = ('F','M');

    my $sql = "select xid,sex,birth from patients where sid=$sid and pid=$pid";
    my($xid,$sex,$birth) = $dbh->selectrow_array($sql);
    print p("$xid, $sex, $birth") if $D;

    print start_blockquote, start_form;
    print h2('Edit patient details');
    print start_table({width=>'95%',border=>1,cellspacing=>0,cellpadding=>10});
    print start_Tr, start_td;
    print start_table({width=>'100%',cellpadding=>'5'}), start_Tr;
    print td(['Site' . br . font({color=>'grey'},$sids{$sid}),
	      'Patient ID #' . br . font({color=>'grey'}, $pid),
	      'Patient Code (ext)' . br .
	      textfield(-name=>'xid0',size=>'16',maxlength=>'64',default=>$xid),
	      'Year of birth' . br .
	      textfield(-name=>'birth0',size=>'4',maxlength=>'4',default=>$birth),
	      'Sex' . br .
	      popup_menu(-name=>'sex0',-values=>\@sexs,-labels=>\%sexs,default=>$sex)]);
    print end_Tr, end_table;
    print end_td, end_Tr, end_table;

    print table({align=>'center',width=>'50%',cellspacing=>'10'},
		Tr(th([submit(-name=>'submit',value=>'Update'),
		       defaults('Cancel')])));
    print hidden(-name=>'sid',default=>$sid,force=>1);
    print hidden(-name=>'pid',default=>$pid,force=>1);
    print hidden(-name=>'mode',default=>'pedt',force=>1);
    print end_form, end_blockquote;

    Pat_Upt() if $submit;
}

sub Pat_Upt {
    print hr;

    for my $v (qw(sid pid xid0 birth0 sex0))  { $$v = param($v); }
    ($sex) = $sex0 =~ /([MF])/;
    ($birth) = $birth0 =~ /(\d+)/;
    $xid0 =~ s/^\s*|\s*$//g; $xid0 =~ s/\s/_/g; #report subst?
    ($xid) = $xid0 =~ /([A-Za-z0-9.,ÅåÄäÖöÉéÈèÜü\/-]+)/;

    print p("sid=$sid ; pid=$pid ; xid=$xid ; sex=$sex ; birth=$birth") if $D;
    unless($sid) { Fret('Please specify a Site.'); return(); }

    my $ptab = sprintf "pat%04d", $sid; my $lid;
    my ($pid0) = $dbh->selectrow_array("select pid from $ptab where xid='$xid' " .
				      "and pid != $pid");

    if ($pid0) {
	Fret("Patient Code '$xid' already registered for Site $sid. " . br .
	     a({href=>url . "?mode=pedt;sid=$sid;pid=$pid0"}, 'Edit details') .
	     ' for that patient.');
    } elsif($xid ne $xid0) {
	Fret("Some unexpected characters found in Patient Code. " .
	     "Please fix or file an error report.");
    } elsif((!$birth && $birth ne '0') || $birth > $year) {
	Fret( "Missing or misunderstood 'birthyear'. " .
	      "Please enter approximate age (or year of birth).");
    } elsif(!$sex) {
	Fret('Please specify sex of patient.');
    } else {
	$birth = $year - $birth if $birth < 200;
	$dbh->do("update $ptab set xid='$xid',sex='$sex',birth=$birth where pid=$pid");
	print p("update $ptab set xid='$xid',sex='$sex',birth=$birth where pid=$pid") if $D;
	$lid = sprintf "P%04d-%04d", $sid, $pid;
	unless($xid) {
	    $xid = $lid;
	    $dbh->do("update $ptab set xid='$xid' where pid=$pid");
	    print p("update $ptab set xid='$xid' where pid=$pid") if $D;
	    Fret("Patient Code not specified so will use '$xid'.");
	}
	print h3("Patient '$xid' ('$lid') has been updated.");
	print br,'You may wish to: ',
	ul(li(['Record an ' . a({href=>"infadm.cgi?sid=$sid;pid=$pid"}, 'infection'),
	       'View ' . a({href=>".?hit=$sid:$pid"}, 'patient summary'),
	       'Add a ' . a({href=>url}, 'new patient')]));
	print p("To re-edit this patient, simply change the details " .
		"above and click 'Update' again.");
    }
}


sub Fret {
    my $v = $_[0];
    return unless $v;
    print p(font({size=>'+1',color=>'green'},$v));
}
